# Generated by Django 5.0.3 on 2024-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbldepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
