# Generated by Django 5.0.3 on 2024-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_tbldoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10, null=True)),
                ('lastname', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('purposeofvisit', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
