# Generated by Django 5.0.3 on 2024-04-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_tblappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextappointment', models.CharField(max_length=10, null=True)),
                ('appointmentdate', models.CharField(max_length=10, null=True)),
                ('medicine', models.CharField(max_length=10, null=True)),
                ('payment', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
