# Generated by Django 5.0.3 on 2024-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_tblreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('subject', models.CharField(max_length=10, null=True)),
                ('message', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
