# Generated by Django 5.0.3 on 2024-04-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_tblcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblmedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=10, null=True)),
                ('medicinecode', models.CharField(max_length=10, null=True)),
                ('medicineprice', models.CharField(max_length=10, null=True)),
                ('amountofmedicine', models.CharField(max_length=10, null=True)),
                ('expirydate', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
